# Generated by Django 4.2.4 on 2023-08-10 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessory_category_name', models.CharField(choices=[('tools', 'Tools'), ('vase', 'Vase'), ('supplies', 'Supplies')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_category_name', models.CharField(choices=[('flowering', 'Flowering'), ('non-flowering', 'Non-flowering'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('succulents', 'Succulents'), ('medicinal', 'Medicinal')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.PositiveIntegerField()),
                ('product_type', models.CharField(choices=[('plant', 'Plant'), ('accessory', 'Access0ry')], max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('product_description', models.TextField()),
                ('product_image', models.ImageField(upload_to='product_images')),
                ('quantity_available', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plant_store.products')),
                ('plant_species', models.CharField(max_length=60)),
                ('plant_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_store.plantcategory')),
            ],
            bases=('plant_store.products',),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('products_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='plant_store.products')),
                ('accessory_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plant_store.accessorycategory')),
            ],
            bases=('plant_store.products',),
        ),
    ]
